### PR TITLE
Allow workflow to update editor draft

### PR DESCRIPTION
**Pull request by ionut-arm**

### CODE REVIEW

**Comment by ionut-arm** [comment]
NB: Adding this because of the recent CI failures and seems I can't change the permissions on the repo to allow "Write" for workflows.

**Comment by yogeshbdeshpande** [comment]
@ionut-arm : Does this pass the CI. I do not see that ?

**Comment by ionut-arm** [comment]
> @ionut-arm : Does this pass the CI. I do not see that ?

True, I'm not sure, the CI only runs on changes to `main` (since the CI also deploys to Github Pages...)

**Comment by yogeshbdeshpande** [comment]
> > @ionut-arm : Does this pass the CI. I do not see that ?
> 
> True, I'm not sure, the CI only runs on changes to `main` (since the CI also deploys to Github Pages...)

CI should be able to run from PR branch as well.., I will share some example, offline, as that link, may not fit the context of this conversation!

**Comment by yaronf** [comment]
> NB: Adding this because of the recent CI failures and seems I can't change the permissions on the repo to allow "Write" for workflows.

@ionut-arm I see you are an Admin on this repo, so I'm surprised.

More generally, if this becomes too messy, we could recreate the repo based on Martin Thomson's template repo. Though I don't know how to import/move the issues.

Having said that, this is not something you do just before the I-D cut-off.

**Comment by yogeshbdeshpande** [comment]
> > NB: Adding this because of the recent CI failures and seems I can't change the permissions on the repo to allow "Write" for workflows.
> 
> @ionut-arm I see you are an Admin on this repo, so I'm surprised.
> 
> More generally, if this becomes too messy, we could recreate the repo based on Martin Thomson's template repo. Though I don't know how to import/move the issues.
> 
> Having said that, this is not something you do just before the I-D cut-off.

I agree withh Yaron, if stuff builds locally on your setup, just submit the ID using Manual Process, instead of sweating on CI issues for now.

**Comment by ionut-arm** [comment]
Ok, I've tested it in my fork: https://github.com/ionut-arm/draft-tls-attestation/actions/runs/9838751664/job/27159313906

Should work as expected. I'll submit the I-D manually, of course, this is just for the editor's draft.

**Comment by ionut-arm** [comment]
> @ionut-arm TBH I'm not sure you need to line that you added. See https://github.com/yaronf/wimse-s2s/blob/main/.github/workflows/ghpages.yml

Ah, I see that's using a different workflow, I do wonder if that's why it takes an extra input.

> I see you are an Admin on this repo, so I'm surprised.

I was equally surprised, I made myself an admin because I thought it would help, but the option to set workflow permissions to "Read and write permissions" was still greyed out..

Turns out we needed to enable it at org-level. I've fixed it now, so closing the PR! Thanks everyone for the feedback :grin:

**Pull request closed without merging**
